#ifndef hessian_h
#define hessian_h

#include <math.h>
#include <Eigen/Dense>

/**
 * Hesian of neo-hookean density function. Autogenerated in algebra software.
 */

float psi_hessian00(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian00_result;
   psi_hessian00_result = 2*C*(pow(-f11*f22 + f12*f21, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f11*f22 + f12*f21, 2);
   return psi_hessian00_result;

}


float psi_hessian01(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian01_result;
   psi_hessian01_result = -2*C*(-f10*f22 + f12*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f10*f22 + f12*f20)*(-f11*f22 + f12*f21);
   return psi_hessian01_result;

}


float psi_hessian02(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian02_result;
   psi_hessian02_result = 2*C*(-f10*f21 + f11*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f10*f21 + f11*f20)*(-f11*f22 + f12*f21);
   return psi_hessian02_result;

}


float psi_hessian03(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian03_result;
   psi_hessian03_result = -2*C*(-f01*f22 + f02*f21)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f01*f22 + f02*f21)*(-f11*f22 + f12*f21);
   return psi_hessian03_result;

}


float psi_hessian04(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian04_result;
   psi_hessian04_result = 2*C*(f22/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f22 + f02*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f22*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f22 + f02*f20)*(-f11*f22 + f12*f21);
   return psi_hessian04_result;

}


float psi_hessian05(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian05_result;
   psi_hessian05_result = -2*C*(f21/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f21 + f01*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f21*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f21 + f01*f20)*(-f11*f22 + f12*f21);
   return psi_hessian05_result;

}


float psi_hessian06(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian06_result;
   psi_hessian06_result = 2*C*(-f01*f12 + f02*f11)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f01*f12 + f02*f11)*(-f11*f22 + f12*f21);
   return psi_hessian06_result;

}


float psi_hessian07(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian07_result;
   psi_hessian07_result = -2*C*(f12/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f12*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f12 + f02*f10)*(-f11*f22 + f12*f21);
   return psi_hessian07_result;

}


float psi_hessian08(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian08_result;
   psi_hessian08_result = 2*C*(f11/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f11*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f11 + f01*f10)*(-f11*f22 + f12*f21);
   return psi_hessian08_result;

}


float psi_hessian10(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian10_result;
   psi_hessian10_result = -2*C*(-f10*f22 + f12*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f10*f22 + f12*f20)*(-f11*f22 + f12*f21);
   return psi_hessian10_result;

}


float psi_hessian11(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian11_result;
   psi_hessian11_result = 2*C*(pow(-f10*f22 + f12*f20, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f10*f22 + f12*f20, 2);
   return psi_hessian11_result;

}


float psi_hessian12(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian12_result;
   psi_hessian12_result = -2*C*(-f10*f21 + f11*f20)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f10*f21 + f11*f20)*(-f10*f22 + f12*f20);
   return psi_hessian12_result;

}


float psi_hessian13(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian13_result;
   psi_hessian13_result = 2*C*(-f22/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f22 + f02*f21)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f22*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f01*f22 + f02*f21)*(-f10*f22 + f12*f20);
   return psi_hessian13_result;

}


float psi_hessian14(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian14_result;
   psi_hessian14_result = -2*C*(-f00*f22 + f02*f20)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f22 + f02*f20)*(-f10*f22 + f12*f20);
   return psi_hessian14_result;

}


float psi_hessian15(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian15_result;
   psi_hessian15_result = 2*C*(f20/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f21 + f01*f20)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f20*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f21 + f01*f20)*(-f10*f22 + f12*f20);
   return psi_hessian15_result;

}


float psi_hessian16(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian16_result;
   psi_hessian16_result = -2*C*(-f12/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f12 + f02*f11)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f12*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f01*f12 + f02*f11)*(-f10*f22 + f12*f20);
   return psi_hessian16_result;

}


float psi_hessian17(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian17_result;
   psi_hessian17_result = 2*C*(-f00*f12 + f02*f10)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f12 + f02*f10)*(-f10*f22 + f12*f20);
   return psi_hessian17_result;

}


float psi_hessian18(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian18_result;
   psi_hessian18_result = -2*C*(f10/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f10*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f11 + f01*f10)*(-f10*f22 + f12*f20);
   return psi_hessian18_result;

}


float psi_hessian20(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian20_result;
   psi_hessian20_result = 2*C*(-f10*f21 + f11*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f10*f21 + f11*f20)*(-f11*f22 + f12*f21);
   return psi_hessian20_result;

}


float psi_hessian21(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian21_result;
   psi_hessian21_result = -2*C*(-f10*f21 + f11*f20)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f10*f21 + f11*f20)*(-f10*f22 + f12*f20);
   return psi_hessian21_result;

}


float psi_hessian22(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian22_result;
   psi_hessian22_result = 2*C*(pow(-f10*f21 + f11*f20, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f10*f21 + f11*f20, 2);
   return psi_hessian22_result;

}


float psi_hessian23(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian23_result;
   psi_hessian23_result = -2*C*(-f21/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f22 + f02*f21)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f21*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f01*f22 + f02*f21)*(-f10*f21 + f11*f20);
   return psi_hessian23_result;

}


float psi_hessian24(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian24_result;
   psi_hessian24_result = 2*C*(-f20/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f22 + f02*f20)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f20*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f22 + f02*f20)*(-f10*f21 + f11*f20);
   return psi_hessian24_result;

}


float psi_hessian25(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian25_result;
   psi_hessian25_result = -2*C*(-f00*f21 + f01*f20)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f21 + f01*f20)*(-f10*f21 + f11*f20);
   return psi_hessian25_result;

}


float psi_hessian26(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian26_result;
   psi_hessian26_result = 2*C*(-f11/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f12 + f02*f11)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f11*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f01*f12 + f02*f11)*(-f10*f21 + f11*f20);
   return psi_hessian26_result;

}


float psi_hessian27(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian27_result;
   psi_hessian27_result = -2*C*(-f10/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f10*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f12 + f02*f10)*(-f10*f21 + f11*f20);
   return psi_hessian27_result;

}


float psi_hessian28(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian28_result;
   psi_hessian28_result = 2*C*(-f00*f11 + f01*f10)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f11 + f01*f10)*(-f10*f21 + f11*f20);
   return psi_hessian28_result;

}


float psi_hessian30(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian30_result;
   psi_hessian30_result = -2*C*(-f01*f22 + f02*f21)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f01*f22 + f02*f21)*(-f11*f22 + f12*f21);
   return psi_hessian30_result;

}


float psi_hessian31(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian31_result;
   psi_hessian31_result = 2*C*(-f22/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f22 + f02*f21)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f22*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f01*f22 + f02*f21)*(-f10*f22 + f12*f20);
   return psi_hessian31_result;

}


float psi_hessian32(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian32_result;
   psi_hessian32_result = -2*C*(-f21/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f22 + f02*f21)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f21*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f01*f22 + f02*f21)*(-f10*f21 + f11*f20);
   return psi_hessian32_result;

}


float psi_hessian33(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian33_result;
   psi_hessian33_result = 2*C*(pow(-f01*f22 + f02*f21, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f01*f22 + f02*f21, 2);
   return psi_hessian33_result;

}


float psi_hessian34(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian34_result;
   psi_hessian34_result = -2*C*(-f00*f22 + f02*f20)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f22 + f02*f20)*(-f01*f22 + f02*f21);
   return psi_hessian34_result;

}


float psi_hessian35(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian35_result;
   psi_hessian35_result = 2*C*(-f00*f21 + f01*f20)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f21 + f01*f20)*(-f01*f22 + f02*f21);
   return psi_hessian35_result;

}


float psi_hessian36(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian36_result;
   psi_hessian36_result = -2*C*(-f01*f12 + f02*f11)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f01*f12 + f02*f11)*(-f01*f22 + f02*f21);
   return psi_hessian36_result;

}


float psi_hessian37(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian37_result;
   psi_hessian37_result = 2*C*(f02/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f02*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f12 + f02*f10)*(-f01*f22 + f02*f21);
   return psi_hessian37_result;

}


float psi_hessian38(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian38_result;
   psi_hessian38_result = -2*C*(f01/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f01*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f11 + f01*f10)*(-f01*f22 + f02*f21);
   return psi_hessian38_result;

}


float psi_hessian40(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian40_result;
   psi_hessian40_result = 2*C*(f22/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f22 + f02*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f22*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f22 + f02*f20)*(-f11*f22 + f12*f21);
   return psi_hessian40_result;

}


float psi_hessian41(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian41_result;
   psi_hessian41_result = -2*C*(-f00*f22 + f02*f20)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f22 + f02*f20)*(-f10*f22 + f12*f20);
   return psi_hessian41_result;

}


float psi_hessian42(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian42_result;
   psi_hessian42_result = 2*C*(-f20/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f22 + f02*f20)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f20*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f22 + f02*f20)*(-f10*f21 + f11*f20);
   return psi_hessian42_result;

}


float psi_hessian43(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian43_result;
   psi_hessian43_result = -2*C*(-f00*f22 + f02*f20)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f22 + f02*f20)*(-f01*f22 + f02*f21);
   return psi_hessian43_result;

}


float psi_hessian44(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian44_result;
   psi_hessian44_result = 2*C*(pow(-f00*f22 + f02*f20, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f00*f22 + f02*f20, 2);
   return psi_hessian44_result;

}


float psi_hessian45(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian45_result;
   psi_hessian45_result = -2*C*(-f00*f21 + f01*f20)*(-f00*f22 + f02*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f21 + f01*f20)*(-f00*f22 + f02*f20);
   return psi_hessian45_result;

}


float psi_hessian46(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian46_result;
   psi_hessian46_result = 2*C*(-f02/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f22 + f02*f20)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f02*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f22 + f02*f20)*(-f01*f12 + f02*f11);
   return psi_hessian46_result;

}


float psi_hessian47(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian47_result;
   psi_hessian47_result = -2*C*(-f00*f12 + f02*f10)*(-f00*f22 + f02*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f12 + f02*f10)*(-f00*f22 + f02*f20);
   return psi_hessian47_result;

}


float psi_hessian48(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian48_result;
   psi_hessian48_result = 2*C*(f00/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f00*f22 + f02*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f00*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f11 + f01*f10)*(-f00*f22 + f02*f20);
   return psi_hessian48_result;

}


float psi_hessian50(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian50_result;
   psi_hessian50_result = -2*C*(f21/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f21 + f01*f20)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f21*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f21 + f01*f20)*(-f11*f22 + f12*f21);
   return psi_hessian50_result;

}


float psi_hessian51(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian51_result;
   psi_hessian51_result = 2*C*(f20/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f21 + f01*f20)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f20*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f21 + f01*f20)*(-f10*f22 + f12*f20);
   return psi_hessian51_result;

}


float psi_hessian52(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian52_result;
   psi_hessian52_result = -2*C*(-f00*f21 + f01*f20)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f21 + f01*f20)*(-f10*f21 + f11*f20);
   return psi_hessian52_result;

}


float psi_hessian53(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian53_result;
   psi_hessian53_result = 2*C*(-f00*f21 + f01*f20)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f21 + f01*f20)*(-f01*f22 + f02*f21);
   return psi_hessian53_result;

}


float psi_hessian54(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian54_result;
   psi_hessian54_result = -2*C*(-f00*f21 + f01*f20)*(-f00*f22 + f02*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f21 + f01*f20)*(-f00*f22 + f02*f20);
   return psi_hessian54_result;

}


float psi_hessian55(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian55_result;
   psi_hessian55_result = 2*C*(pow(-f00*f21 + f01*f20, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f00*f21 + f01*f20, 2);
   return psi_hessian55_result;

}


float psi_hessian56(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian56_result;
   psi_hessian56_result = -2*C*(-f01/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f21 + f01*f20)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f01*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f21 + f01*f20)*(-f01*f12 + f02*f11);
   return psi_hessian56_result;

}


float psi_hessian57(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian57_result;
   psi_hessian57_result = 2*C*(-f00/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f00*f21 + f01*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f00*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f12 + f02*f10)*(-f00*f21 + f01*f20);
   return psi_hessian57_result;

}


float psi_hessian58(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian58_result;
   psi_hessian58_result = -2*C*(-f00*f11 + f01*f10)*(-f00*f21 + f01*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f11 + f01*f10)*(-f00*f21 + f01*f20);
   return psi_hessian58_result;

}


float psi_hessian60(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian60_result;
   psi_hessian60_result = 2*C*(-f01*f12 + f02*f11)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f01*f12 + f02*f11)*(-f11*f22 + f12*f21);
   return psi_hessian60_result;

}


float psi_hessian61(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian61_result;
   psi_hessian61_result = -2*C*(-f12/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f12 + f02*f11)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f12*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f01*f12 + f02*f11)*(-f10*f22 + f12*f20);
   return psi_hessian61_result;

}


float psi_hessian62(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian62_result;
   psi_hessian62_result = 2*C*(-f11/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f01*f12 + f02*f11)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f11*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f01*f12 + f02*f11)*(-f10*f21 + f11*f20);
   return psi_hessian62_result;

}


float psi_hessian63(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian63_result;
   psi_hessian63_result = -2*C*(-f01*f12 + f02*f11)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f01*f12 + f02*f11)*(-f01*f22 + f02*f21);
   return psi_hessian63_result;

}


float psi_hessian64(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian64_result;
   psi_hessian64_result = 2*C*(-f02/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f22 + f02*f20)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f02*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f22 + f02*f20)*(-f01*f12 + f02*f11);
   return psi_hessian64_result;

}


float psi_hessian65(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian65_result;
   psi_hessian65_result = -2*C*(-f01/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f21 + f01*f20)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f01*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f21 + f01*f20)*(-f01*f12 + f02*f11);
   return psi_hessian65_result;

}


float psi_hessian66(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian66_result;
   psi_hessian66_result = 2*C*(pow(-f01*f12 + f02*f11, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f01*f12 + f02*f11, 2);
   return psi_hessian66_result;

}


float psi_hessian67(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian67_result;
   psi_hessian67_result = -2*C*(-f00*f12 + f02*f10)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f12 + f02*f10)*(-f01*f12 + f02*f11);
   return psi_hessian67_result;

}


float psi_hessian68(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian68_result;
   psi_hessian68_result = 2*C*(-f00*f11 + f01*f10)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f11 + f01*f10)*(-f01*f12 + f02*f11);
   return psi_hessian68_result;

}


float psi_hessian70(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian70_result;
   psi_hessian70_result = -2*C*(f12/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f12*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f12 + f02*f10)*(-f11*f22 + f12*f21);
   return psi_hessian70_result;

}


float psi_hessian71(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian71_result;
   psi_hessian71_result = 2*C*(-f00*f12 + f02*f10)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f12 + f02*f10)*(-f10*f22 + f12*f20);
   return psi_hessian71_result;

}


float psi_hessian72(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian72_result;
   psi_hessian72_result = -2*C*(-f10/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f10*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f12 + f02*f10)*(-f10*f21 + f11*f20);
   return psi_hessian72_result;

}


float psi_hessian73(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian73_result;
   psi_hessian73_result = 2*C*(f02/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f02*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f12 + f02*f10)*(-f01*f22 + f02*f21);
   return psi_hessian73_result;

}


float psi_hessian74(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian74_result;
   psi_hessian74_result = -2*C*(-f00*f12 + f02*f10)*(-f00*f22 + f02*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f12 + f02*f10)*(-f00*f22 + f02*f20);
   return psi_hessian74_result;

}


float psi_hessian75(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian75_result;
   psi_hessian75_result = 2*C*(-f00/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f12 + f02*f10)*(-f00*f21 + f01*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f00*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f12 + f02*f10)*(-f00*f21 + f01*f20);
   return psi_hessian75_result;

}


float psi_hessian76(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian76_result;
   psi_hessian76_result = -2*C*(-f00*f12 + f02*f10)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f12 + f02*f10)*(-f01*f12 + f02*f11);
   return psi_hessian76_result;

}


float psi_hessian77(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian77_result;
   psi_hessian77_result = 2*C*(pow(-f00*f12 + f02*f10, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f00*f12 + f02*f10, 2);
   return psi_hessian77_result;

}


float psi_hessian78(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian78_result;
   psi_hessian78_result = -2*C*(-f00*f11 + f01*f10)*(-f00*f12 + f02*f10)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f11 + f01*f10)*(-f00*f12 + f02*f10);
   return psi_hessian78_result;

}


float psi_hessian80(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian80_result;
   psi_hessian80_result = 2*C*(f11/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f11*f22 + f12*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f11*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f11 + f01*f10)*(-f11*f22 + f12*f21);
   return psi_hessian80_result;

}


float psi_hessian81(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian81_result;
   psi_hessian81_result = -2*C*(f10/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f10*f22 + f12*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f10*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f11 + f01*f10)*(-f10*f22 + f12*f20);
   return psi_hessian81_result;

}


float psi_hessian82(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian82_result;
   psi_hessian82_result = 2*C*(-f00*f11 + f01*f10)*(-f10*f21 + f11*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f11 + f01*f10)*(-f10*f21 + f11*f20);
   return psi_hessian82_result;

}


float psi_hessian83(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian83_result;
   psi_hessian83_result = -2*C*(f01/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f01*f22 + f02*f21)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) + 2*D*f01*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) - 2*D*(-f00*f11 + f01*f10)*(-f01*f22 + f02*f21);
   return psi_hessian83_result;

}


float psi_hessian84(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian84_result;
   psi_hessian84_result = 2*C*(f00/(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11)) + (-f00*f11 + f01*f10)*(-f00*f22 + f02*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2)) - 2*D*f00*(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11) + 1) + 2*D*(-f00*f11 + f01*f10)*(-f00*f22 + f02*f20);
   return psi_hessian84_result;

}


float psi_hessian85(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian85_result;
   psi_hessian85_result = -2*C*(-f00*f11 + f01*f10)*(-f00*f21 + f01*f20)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f11 + f01*f10)*(-f00*f21 + f01*f20);
   return psi_hessian85_result;

}


float psi_hessian86(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian86_result;
   psi_hessian86_result = 2*C*(-f00*f11 + f01*f10)*(-f01*f12 + f02*f11)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 2*D*(-f00*f11 + f01*f10)*(-f01*f12 + f02*f11);
   return psi_hessian86_result;

}


float psi_hessian87(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian87_result;
   psi_hessian87_result = -2*C*(-f00*f11 + f01*f10)*(-f00*f12 + f02*f10)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) - 2*D*(-f00*f11 + f01*f10)*(-f00*f12 + f02*f10);
   return psi_hessian87_result;

}


float psi_hessian88(float C, float D, float f00, float f01, float f02, float f10, float f11, float f12, float f20, float f21, float f22) {

   float psi_hessian88_result;
   psi_hessian88_result = 2*C*(pow(-f00*f11 + f01*f10, 2)/pow(f00*(-f11*f22 + f12*f21) - f10*(-f01*f22 + f02*f21) + f20*(-f01*f12 + f02*f11), 2) + 1) + 2*D*pow(-f00*f11 + f01*f10, 2);
   return psi_hessian88_result;

}

Eigen::MatrixXf psi_hessian(float C, float D, Eigen::VectorXf f) {
    Eigen::MatrixXf psi_hess = Eigen::MatrixXf::Zero(9,9);
    
    psi_hess(0,0) = psi_hessian00(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,1) = psi_hessian01(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,2) = psi_hessian02(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,3) = psi_hessian03(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,4) = psi_hessian04(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,5) = psi_hessian05(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,6) = psi_hessian06(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,7) = psi_hessian07(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(0,8) = psi_hessian08(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,0) = psi_hessian10(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,1) = psi_hessian11(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,2) = psi_hessian12(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,3) = psi_hessian13(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,4) = psi_hessian14(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,5) = psi_hessian15(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,6) = psi_hessian16(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,7) = psi_hessian17(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(1,8) = psi_hessian18(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,0) = psi_hessian20(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,1) = psi_hessian21(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,2) = psi_hessian22(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,3) = psi_hessian23(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,4) = psi_hessian24(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,5) = psi_hessian25(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,6) = psi_hessian26(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,7) = psi_hessian27(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(2,8) = psi_hessian28(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,0) = psi_hessian30(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,1) = psi_hessian31(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,2) = psi_hessian32(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,3) = psi_hessian33(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,4) = psi_hessian34(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,5) = psi_hessian35(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,6) = psi_hessian36(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,7) = psi_hessian37(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(3,8) = psi_hessian38(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,0) = psi_hessian40(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,1) = psi_hessian41(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,2) = psi_hessian42(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,3) = psi_hessian43(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,4) = psi_hessian44(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,5) = psi_hessian45(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,6) = psi_hessian46(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,7) = psi_hessian47(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(4,8) = psi_hessian48(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,0) = psi_hessian50(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,1) = psi_hessian51(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,2) = psi_hessian52(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,3) = psi_hessian53(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,4) = psi_hessian54(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,5) = psi_hessian55(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,6) = psi_hessian56(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,7) = psi_hessian57(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(5,8) = psi_hessian58(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,0) = psi_hessian60(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,1) = psi_hessian61(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,2) = psi_hessian62(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,3) = psi_hessian63(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,4) = psi_hessian64(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,5) = psi_hessian65(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,6) = psi_hessian66(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,7) = psi_hessian67(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(6,8) = psi_hessian68(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,0) = psi_hessian70(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,1) = psi_hessian71(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,2) = psi_hessian72(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,3) = psi_hessian73(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,4) = psi_hessian74(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,5) = psi_hessian75(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,6) = psi_hessian76(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,7) = psi_hessian77(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(7,8) = psi_hessian78(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,0) = psi_hessian80(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,1) = psi_hessian81(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,2) = psi_hessian82(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,3) = psi_hessian83(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,4) = psi_hessian84(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,5) = psi_hessian85(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,6) = psi_hessian86(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,7) = psi_hessian87(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    psi_hess(8,8) = psi_hessian88(C, D, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8]);
    
    return psi_hess;
}

#endif /* hessian_h */
